### PR TITLE
Add extension instruction for Emacs

### PR DESCRIPTION
**Pull request by jpthiele**

### CODE REVIEW

**Comment by jpthiele** [comment]
@j-fu @pjaap FYI

**Comment by fredrikekre** [comment]
> and that the alias is set

So the Emacs will run the command through a shell where the rc file defining the alias have been loaded?

**Comment by jpthiele** [comment]
We realized in testing that that is sadly not the case.
What works is putting a shell script in `PATH` that can be called. We could add that to the PR if you want.
Might also be useful for others to not use the alias?

**Comment by fredrikekre** [comment]
Looking at https://github.com/radian-software/apheleia/blob/main/apheleia-formatters.el it seems like you can include a more elaborate command (e.g. something similar to https://github.com/fredrikekre/Runic.jl/blob/6bd8eaebed5b19859cd6b2771c05c053ad482384/README.md#L132-L133 ?

**Comment by jpthiele** [comment]
I had tried a few options but the error output always looked the same if I only split part of the command into individual blocks of `"<sth>"` but splitting it completely worked.

**Pull request merged**
